export const data = {
  products: [
    {
      id: '1',
      name: 'Hats(men)',
      image: '/images/men_hat.webp',
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality hat',
    },
    {
      id: '2',
      name: 'Hats(women)',
      image: '/images/women_hat.jpg',
      price: 250,
      countInStock: 0,
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '3',
      name: 'Jeans(men)',
      image: '/images/men_jeans.webp',
      price: 25,
      countInStock: 15,
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      id: '4',
      name: 'Jeans(women)',
      image: '/images/women_jeans.jpg',
      price: 65,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '5',
      name: 'T-shirts(men)',
      image: '/images/men_t-shirt.jpg',
      price: 65,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '6',
      name: 'T-shirts(women)',
      image: '/images/women_t-shirt.jpg',
      price: 65,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '7',
      name: 'Hoodie(women)',
      image: '/images/women_hoodie.webp',
      price: 65,
      countInStock: 0,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '8',
      name: 'Hoodie(men)',
      image: '/images/men_hoodie.webp',
      price: 65,
      countInStock: 5,
      rating: 4,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
}
